[project]
name = "advent-of-code-2024"
version = "0.1.0"
requires-python = ">=3.14"

[dependency-groups]
dev = [
    "cookiecutter>=2.6.0",
    "copier>=9.8.0",
    "ipython>=9.3.0",
    "parse>=1.20.2",
    "pytest",
    "ruff",
    "ty",
]

[tool.uv]
prerelease = "allow"
