[project]
name = "advent-of-code-2024"
version = "0.1.0"
requires-python = ">=3.14"

[dependency-groups]
dev = [
    "cookiecutter",
    "copier",
    "ipython",
    "parse",
    "pytest",
    "ruff==0.14.13",
    "ty==0.0.8",
]

[tool.uv]
prerelease = "allow"
